language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: R6jb042mBTFTX0zxvY1Lg+UCxMzOBWCDYf/LNCLF2LU1R65X4hrrXYXnKCiaUJ+IDhPvnnuDxqI9v0QP624Mu0vXKQps5C4/rsTa2drk9YbTJvswHicHasd7dJLKAcUz2c84j6qo7P1SkWFVFNBSGzNdPhAuUTaYEP+Xmp65WbnfKqwiyHm1u4koWDPK341x5+uIa4v6+KJZc32CWDXYCrruAjlv4QwGSLQUmb51ld5xjFuib2nnwKE27MxBE+aBY0SJaL2Vp19UB6keRe3HfhipD7i97E0ceXtv/Sc/msQLD+lHKEBz25gO6FYphEGX9evUrl84EsjX/q1dO9KVmEOhd70YnpAkyeNuUMbVYoVuupY7RLp2yrg3XNsmjcQxKBPuvlxPGfA35/tftgwXGio4O6ML3phTNLrdHN85uXmoITN7V8wPlVNYktk2p3/a0lVQsNqHtknLef5wtRLXTUWD1WaB0sMXqfHQqlV1qYDT1m06v4Hf7XRdDXr9MTSTWLEKALo86wCTqXNeDzUaXjD1y+iiEU2D/CmDbNZNA4rkCbaphv21MnRh5NwC64geR4pXNNeqG5KCar8DO0wRfuDJwenHTxaSxT/5ZA8hU2SbD4Sgjh5WNnpiY2WlRdBzeimw+PuecjJAtknxVoBEuHbhjS04JnOrbCPZjnN0WLY=
  app: evening-woodland-10892